"""
Database Models for AI Browser Automation
"""
import json
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import DeclarativeBase
from app.utils.encryption import credential_encryption


class Base(DeclarativeBase):
    pass


db = SQLAlchemy(model_class=Base)


class AutomationPlan(db.Model):
    """Model for storing automation plans generated by Planner Agent"""
    
    __tablename__ = 'automation_plans'
    
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)
    execution_id = db.Column(db.Integer, db.ForeignKey('execution_history.id'), nullable=True)
    
    goal = db.Column(db.Text, nullable=False)
    start_url = db.Column(db.Text, nullable=False)
    plan_yaml = db.Column(db.Text, nullable=False)
    validated_locators = db.Column(db.Text, nullable=True)
    plan_metadata = db.Column(db.Text, nullable=True)
    
    def to_dict(self):
        """Convert model to dictionary"""
        return {
            'id': self.id,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'execution_id': self.execution_id,
            'goal': self.goal,
            'start_url': self.start_url,
            'plan_yaml': self.plan_yaml,
            'validated_locators': self.validated_locators,
            'plan_metadata': self.plan_metadata
        }


class GeneratedScript(db.Model):
    """Model for storing Python Playwright scripts generated by Generator Agent"""
    
    __tablename__ = 'generated_scripts'
    __table_args__ = (
        db.Index('idx_execution_created', 'execution_id', 'created_at'),
    )
    
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)
    execution_id = db.Column(db.Integer, db.ForeignKey('execution_history.id'), nullable=True, index=True)
    plan_id = db.Column(db.Integer, db.ForeignKey('automation_plans.id'), nullable=True)
    
    script_type = db.Column(db.String(20), nullable=False, default='original')
    python_code = db.Column(db.Text, nullable=False)
    script_hash = db.Column(db.String(64), nullable=True, index=True)
    
    is_healed = db.Column(db.Boolean, nullable=False, default=False)
    healing_iterations = db.Column(db.Integer, nullable=True, default=0)
    
    def to_dict(self):
        """Convert model to dictionary"""
        return {
            'id': self.id,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'execution_id': self.execution_id,
            'plan_id': self.plan_id,
            'script_type': self.script_type,
            'python_code': self.python_code,
            'script_hash': self.script_hash,
            'is_healed': self.is_healed,
            'healing_iterations': self.healing_iterations
        }


class TraceFile(db.Model):
    """Model for storing Playwright trace files for Healer Agent"""
    
    __tablename__ = 'trace_files'
    
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)
    execution_id = db.Column(db.Integer, db.ForeignKey('execution_history.id'), nullable=True)
    script_id = db.Column(db.Integer, db.ForeignKey('generated_scripts.id'), nullable=True)
    
    trace_path = db.Column(db.Text, nullable=False)
    trace_analysis = db.Column(db.Text, nullable=True)
    identified_issues = db.Column(db.Text, nullable=True)
    
    def to_dict(self):
        """Convert model to dictionary"""
        return {
            'id': self.id,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'execution_id': self.execution_id,
            'script_id': self.script_id,
            'trace_path': self.trace_path,
            'trace_analysis': self.trace_analysis,
            'identified_issues': self.identified_issues
        }


class ExecutionHistory(db.Model):
    """Model for storing automation execution history"""
    
    __tablename__ = 'execution_history'
    __table_args__ = (
        db.Index('idx_engine_created', 'engine', 'created_at'),
        db.Index('idx_success_created', 'success', 'created_at'),
    )
    
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)
    
    prompt = db.Column(db.Text, nullable=False)
    engine = db.Column(db.String(50), nullable=False, index=True)
    headless = db.Column(db.Boolean, nullable=False, default=False)
    
    success = db.Column(db.Boolean, nullable=False, default=False, index=True)
    error_message = db.Column(db.Text, nullable=True)
    
    screenshot_path = db.Column(db.Text, nullable=True)  # JSON array of screenshot paths
    execution_logs = db.Column(db.Text, nullable=True)
    
    iterations = db.Column(db.Integer, nullable=True)
    execution_time = db.Column(db.Float, nullable=True)
    
    automation_plans = db.relationship('AutomationPlan', backref='execution', lazy=True)
    generated_scripts = db.relationship('GeneratedScript', backref='execution', lazy=True)
    trace_files = db.relationship('TraceFile', backref='execution', lazy=True)
    
    def to_dict(self):
        """Convert model to dictionary"""
        screenshots = []
        if self.screenshot_path:
            try:
                screenshots = json.loads(self.screenshot_path)
            except (json.JSONDecodeError, TypeError):
                screenshots = [self.screenshot_path] if self.screenshot_path else []
        
        # Get generated and healed scripts
        generated_script = None
        healed_script = None
        
        # Find the most recent generated script (non-healed)
        for script in sorted(self.generated_scripts, key=lambda x: x.created_at, reverse=True):
            if not script.is_healed and not generated_script:
                generated_script = script.python_code
            elif script.is_healed and not healed_script:
                healed_script = script.python_code
        
        return {
            'id': self.id,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'prompt': self.prompt,
            'engine': self.engine,
            'headless': self.headless,
            'success': self.success,
            'error_message': self.error_message,
            'screenshot_path': self.screenshot_path,
            'screenshots': screenshots,
            'execution_logs': self.execution_logs,
            'iterations': self.iterations,
            'execution_time': self.execution_time,
            'generated_script': generated_script,
            'healed_script': healed_script
        }


class CredentialVault(db.Model):
    """Model for securely storing website credentials with encryption"""
    
    __tablename__ = 'credential_vault'
    
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    name = db.Column(db.String(100), nullable=False, unique=True, index=True)
    service = db.Column(db.String(200), nullable=True)
    url = db.Column(db.Text, nullable=True)
    username = db.Column(db.String(200), nullable=True)
    encrypted_value = db.Column(db.Text, nullable=False)
    description = db.Column(db.Text, nullable=True)
    
    def set_credential(self, plaintext_value: str):
        """Encrypt and store a credential value"""
        self.encrypted_value = credential_encryption.encrypt(plaintext_value)
    
    def get_credential(self) -> str:
        """Decrypt and return the credential value"""
        return credential_encryption.decrypt(self.encrypted_value)
    
    def to_dict(self, include_value=False):
        """
        Convert model to dictionary
        
        Args:
            include_value: If True, include the decrypted credential value.
                          Should only be True when actually using the credential.
        """
        result = {
            'id': self.id,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
            'name': self.name,
            'service': self.service,
            'url': self.url,
            'username': self.username,
            'description': self.description
        }
        
        if include_value:
            result['value'] = self.get_credential()
        
        return result
